### ISSUE TITLE
How to inject styles into 'head' rather than 'body'

### ISSUE THREAD

**Issue by judah-firewood** [sparkbox/email-lab#10]
This may be a premailer or assemble question, but wondering if you know of a way to inject styles into 'head' rather than 'body' (general / media queries, not inline styles).

Any help is appreciated. Great tool!

**Comment by nrambeck** [comment]
hi @judah-firewood! That is a Premailer thing, but after some quick testing it looks like newer versions of Premailer put the styles into head instead of body. I created a new branch and PR (#12) that upgrades the `Gemfile` to use the latest version of Premailer. Could you test that branch and tell me if it works for you? If so, maybe work with it a day or 2 to make sure nothing else goes wonky with this new version. After pulling down this branch you'll want to run `bundle install` to upgrade to the new version of Premailer. Thanks!

**Comment by judah-firewood** [comment]
Beautiful! Works perfectly. I’ll definitely work with this for another couple days and let you know if anything comes up. Thank you!

**Comment by nrambeck** [comment]
Hey @judah-firewood, how are things going with these changes? Any issues?

**Comment by nrambeck** [comment]
These changes have been merged in.
